### ISSUE TITLE
Few questions regarding script

### ISSUE THREAD

**Issue by vespuccieth** [hashlips-lab/safe-nft-metadata-provider#23]
Is it possible to make that script starts from token #0 instead of #1? 

If we don't need hidden png/json, can we just leave environmental variable empty/blank?

Also this is my image url in json file: `"image":"http:\/\/tv3-app-vg9pw.ondigitalocean.app\/asset\/1.png"`
What's up with `\/`

Also thank you for this script, this is literally a game changer

**Comment by liarco** [comment]
> Is it possible to make that script starts from token `0` instead of `1`?

Hi @vespuccieth, I'm about to publish a video that shows how you can customize the app to your needs, you will be able to start from there to change any behavior. But as far as I know the ERC721 standard expects token IDs to start from `1`. As a developer I would prefer IDs to start from 0 too, but we have to be compliant to that... 😅

I'm gonna drop the link here as soon as I publish the video. 😉

> If we don't need hidden png/json, can we just leave environmental variable empty/blank?

Everything should work as expected, but your hidden metadata (if requested by any marketplace) will be invalid. I highly suggest having the hidden metadata/assets anyway to be fully compliant... but it's up to you.

> Also this is my image url in json file: "image":"http:\/\/tv3-app-vg9pw.ondigitalocean.app\/asset\/1.png"
> What's up with \/

The JSON code you are showing is perfectly fine. I know that syntax is a bit uncommon, but it's correct as per JSON specifications.

You can see it trying to paste the following code on https://jsoneditoronline.org:
```json
{
  "image": "http:\/\/tv3-app-vg9pw.ondigitalocean.app\/asset\/1.png"
}
```

You will see that the `\/` chars will be highlighted as an escaped sequence for `/`.

> Also thank you for this script, this is literally a game changer

Thank you so much, I really appreciate it. 🙏

**Comment by vespuccieth** [comment]
Great, appreciate it ♥
