### ISSUE TITLE
metadata and erc-7210-collection (infura)

### ISSUE THREAD

**Issue by hrnft** [hashlips-lab/safe-nft-metadata-provider#31]
Hi,

When using both of the safe-metadata-provider and erc721-collection gits, they both use infura should we create a separate project-id for the safemetadata method or use the same one we setup in the erc721-collection for the contract?

**Comment by liarco** [comment]
Hi @hrnft, that's a good question! Using the same for both DAPP and Metadata Provider is fine. 😉

**Comment by hrnft** [comment]
Thank you for the quick response!

And thanks for the great code!
