### ISSUE TITLE
Is this necessary?

### ISSUE THREAD

**Issue by Erickx0** [hashlips-lab/safe-nft-metadata-provider#32]
I'm confused. Why would you have to hide the metadata prior to it being revealed? 

1. Couldn't you just create a list of metadata for the revealed URI and NOT upload the revealed metadata until you'r ready to reveal your collection?
2.Use the art engine to generate new metadata and upload that to IPFS, then point your URI  to the uploaded metadata which would just be a list of jason files depending on your total supply?
3.Just not upload the revealed metadata.

Couldn't you just login to etherscan and use the contract function to change the reveal URI?

Is this process intended for people who have not done any of the previous steps or am I missing some sort of compatibility issues when communicating with truffle/hardhat and the dapp?

Sorry, just trying to understand why this is important. After the reveal, it's really up to the holder what they want to do with the NFT they have minted and showing rarity to the public is kinda important to display publicly that you do plan on awarding those who minted during the whitelist or presale.

**Comment by Erickx0** [comment]
With 3. I meant "Not upload the metadata for the reveled collection UNTIL your ready to reveal the collection. Then you can interact with the contract using etherscan to change the revealed URI to it's newly uploaded URI with the revealed metadata." This would make it impossible to know which uri pertains to each minted URI during the presale. Assuming you upload to a flash drive and store it in a safe location and assuming you actually upload the revealed images and metadata. You can create GIFs to preview your collection.

**Comment by liarco** [comment]
Hi @Erickx0 you questions are absolutely fine and your strategy is correct (reveal just after sold-out). If it was up to me, I would go for it 100%, but in reality many projects can take weeks or months to sell out and users won't wait so long to see their tokens.

This is why having an option to reveal earlier while still going on with minting might be needed.

I hope this makes it clear, let me know if you need any further information.

**Comment by Erickx0** [comment]
Thanks for the reply! I feel that if a holder is too quick to sell before revealing then it should be okay. It's the holders token at that point and trading it before a reveal also has its consequences. What if the holder was to be holding a super rare nft. The artists credibility would increase after successfully uploading the images and metadata pertaining to the randomization of selection since the layers are shuffled. I guess in theory there would be no need to upload more then 2 cids at a time. Possibly just 1 jason file for the image, then including all the attributes with a constant value such as "preview". I think uploading any json files or images is risky because even through the testing stages, it's not to difficult to track back the original contract address and save the information because there is a period of vulnerability after uploading the data to ipfs until the developer implements the new security protocol to protect its data. A true reveal is not revealed until it's time to reveal, even if the launch from whitelist to reveal takes months, days or hours. It's good practice to prove the benefits of holding to anyone minting. I feel like it would increase the value of future minting and grow a larger community anticipating the next drop. It's common to see this type of psychological thinking in similar markets which involve trading. First the fear of missing out needs to be established and demand will increase in the future. You guys have taught me a lot, from launching on remix to using hardhat/truffle/react,etc. I have watched hours of your videos so anytime something new comes up, I consider it creditable. I guess this script helps certain people and may not be needed for others.

**Comment by liarco** [comment]
@Erickx0 thank you for your feedback, I totally agree with your points here. It depends on the way people want to run their collections, I won't judge either strategies, but I would personally see this (at least) as an emergency tool rather than a "requirement".

I'm gonna close this issue, I hope I answered the question, but please feel free to reply if you still need further info about this topic. 😉
