### ISSUE TITLE
Not updating unless server is redeployed

### ISSUE THREAD

**Issue by randytorres** [hashlips-lab/safe-nft-metadata-provider#36]
I have minted a token by the ID of 7 but it won't show unless I rebuild the server (on Digital Ocean). Then if i mint tokenId 8 it won't show again unless I rebuild the server. 

It was previously working a few days ago but today it's requiring a server rebuild everytime. Any idea what the issue could be?

**Comment by liarco** [comment]
Hi @randytorres I can't reproduce this in any way, this seems like a cache issue... did you try running a `bin/console cache:clear` command in console, or even a `rm -rf var/cache` (please pay attention with the second one, because that deletes the given folder recursively).
