### ISSUE TITLE
Runetime logs error?

### ISSUE THREAD

**Issue by M1lfsh4k3** [hashlips-lab/safe-nft-metadata-provider#41]
Hi, followed the youtube guide step by step, the only difference is that i chose Amsterdam instead of Frankfurt..
So everything is deployed and running but Digitalocean app cant open the url for the json files, cant view them.
When it requests get files this is what the logs show:
`[metadata-provider] [2022-04-15 09:49:42] {"message":"Matched route \"get_metadata\".","context":{"route":"get_metadata","route_parameters":{"_route":"get_metadata","_format":"json","_controller":"App\\Controller\\MetadataController","tokenId":"1"},"request_uri":"http://nftslots-app-7b5lb.ondigitalocean.app/metadata/1.json","method":"GET"},"level":200,"level_name":"INFO","channel":"request","datetime":"2022-04-15T09:49:42.341699+00:00","extra":{}}
[metadata-provider] [2022-04-15 09:49:42] {"message":"Checking for authenticator support.","context":{"firewall_name":"main","authenticators":0},"level":100,"level_name":"DEBUG","channel":"security","datetime":"2022-04-15T09:49:42.342362+00:00","extra":{}}
[metadata-provider] [2022-04-15 09:49:42] {"message":"Lock acquired, now computing item \"cached_total_supply_provider.total_supply\"","context":{"key":"cached_total_supply_provider.total_supply"},"level":200,"level_name":"INFO","channel":"cache","datetime":"2022-04-15T09:49:42.405764+00:00","extra":{}}
[metadata-provider] [2022-04-15 09:49:42] {"message":"Uncaught PHP Exception Exception: \"msgData must be a unprefixed hex value.\" at /workspace/vendor/digitaldonkey/ethereum-php/src/Abi.php line 93","context":{"exception":{"class":"Exception","message":"msgData must be a unprefixed hex value.","code":0,"file":"/workspace/vendor/digitaldonkey/ethereum-php/src/Abi.php:93"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2022-04-15T09:49:42.801227+00:00","extra":{}}
[metadata-provider] [2022-04-15 09:49:42] 10.244.7.85 - - [15/Apr/2022:09:49:42 +0000] "GET /metadata/1.json HTTP/1.1" 500 135 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36
`

Also noticed the runtime log keeps running - 408 - logs, is that some kind of error?
Never ending loop:
`[metadata-provider] [2022-04-15 09:46:40] 10.244.25.171 - - [15/Apr/2022:09:46:39 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:46:50] 10.244.5.132 - - [15/Apr/2022:09:46:49 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:46:50] 10.244.25.171 - - [15/Apr/2022:09:46:49 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:47:00] 10.244.5.132 - - [15/Apr/2022:09:46:59 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:47:00] 10.244.25.171 - - [15/Apr/2022:09:46:59 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:47:10] 10.244.5.132 - - [15/Apr/2022:09:47:09 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:47:10] 10.244.25.171 - - [15/Apr/2022:09:47:09 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:47:20] 10.244.5.132 - - [15/Apr/2022:09:47:19 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:47:20] 10.244.25.171 - - [15/Apr/2022:09:47:19 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:47:30] 10.244.5.132 - - [15/Apr/2022:09:47:29 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:47:30] 10.244.25.171 - - [15/Apr/2022:09:47:29 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:47:40] 10.244.5.132 - - [15/Apr/2022:09:47:39 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:47:40] 10.244.25.171 - - [15/Apr/2022:09:47:39 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:47:50] 10.244.5.132 - - [15/Apr/2022:09:47:49 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:47:50] 10.244.25.171 - - [15/Apr/2022:09:47:49 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:48:00] 10.244.5.132 - - [15/Apr/2022:09:47:59 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:48:00] 10.244.25.171 - - [15/Apr/2022:09:47:59 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:48:10] 10.244.5.132 - - [15/Apr/2022:09:48:09 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:48:10] 10.244.25.171 - - [15/Apr/2022:09:48:09 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:48:20] 10.244.5.132 - - [15/Apr/2022:09:48:19 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:48:20] 10.244.25.171 - - [15/Apr/2022:09:48:19 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:48:30] 10.244.5.132 - - [15/Apr/2022:09:48:29 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:48:30] 10.244.25.171 - - [15/Apr/2022:09:48:29 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:48:40] 10.244.5.132 - - [15/Apr/2022:09:48:39 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:48:40] 10.244.25.171 - - [15/Apr/2022:09:48:39 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:48:50] 10.244.5.132 - - [15/Apr/2022:09:48:49 +0000] "-" 408 - "-" "-
[metadata-provider] [2022-04-15 09:48:50] 10.244.25.171 - - [15/Apr/2022:09:48:49 +0000] "-" 408 - "-" "-`

Please help me.

**Comment by M1lfsh4k3** [comment]
Oh snap, is it because my project is not Ethereum but BSC? I remember Infura.io only had the option for Ethereum network

**Comment by M1lfsh4k3** [comment]
Sorry for the spam, but when i request the: https://nftslots-app-7b5lb.ondigitalocean.app/metadata/1.json
The page says:
{"type":"https:\/\/tools.ietf.org\/html\/rfc2616#section-10","title":"An error occurred","status":500,"detail":"Internal Server Error"}

**Comment by M1lfsh4k3** [comment]
Tried creating a Moralis server that supports BSC nad entered the server url instead of the infura url, but nope still no action :/

**Comment by andreleo6** [comment]
Hey, could you fix it? I'm having the same problem

**Comment by M1lfsh4k3** [comment]
Please help its very urgent

**Comment by liarco** [comment]
Hi, I never used this on BSC, but why aren't you simply using the public RPC endpoint for that chain? Instead of Infura you can try this one `https://bsc-dataseed.binance.org`. Let me know if it works.

**Comment by M1lfsh4k3** [comment]
the link you wrote takes me to 404 page not found, tried google but cant find the correct link :) Thanks for helping mate

**Comment by liarco** [comment]
You don't have to open the link, you should set it as the web3 provider in the config (instead of Infura) 😉

**Comment by liarco** [comment]
> I used getblock.io for AVAX, check if they also have BSC

For chains that have official public nodes (e.g. BSC, Polygon, etc.) I would suggest using them, so you won't rely on a third-party service when it's not needed.

**Comment by M1lfsh4k3** [comment]
> You don't have to open the link, you should set it as the web3 provider in the config (instead of Infura) 😉

Oh ok sorry im new to these things ill try that :)

**Comment by M1lfsh4k3** [comment]
Cheers, it worked with the link u provided for bsc :) Thanks
