### ISSUE TITLE
Invalid template URL

### ISSUE THREAD

**Issue by arturbiotonico** [hashlips-lab/safe-nft-metadata-provider#44]
![image](https://user-images.githubusercontent.com/101893195/165119435-320831e5-6360-4572-b796-ba6d400e7718.png)

I got this message when I tried to deploy in the digital ocean. What should I do?

**Comment by arturbiotonico** [comment]
Hi @liarco. Thank you very much for your attention

**Comment by liarco** [comment]
@arturbiotonico this has been fixed with #45. Please let me know if are still having issues.

Thank you.
