### ISSUE TITLE
Misformed URL when replacing image URI

### ISSUE THREAD

**Issue by kokako-loon** [hashlips-lab/safe-nft-metadata-provider#51]
Hello! Great app. Issue with URL replacement 

Looks like the PHP is replacing the image parameter in the json metadata with extra characters. Specifically here’s an example output 

`http:\/\/mydigital-app.ondigitalocean.app\/asset\/1.png `

and the `\/` now means that the image link isn't getting parsed correctly by the browser (goes to `//asset//1.png` instead of `/asset/1.png`

I couldn’t see an obvious place where this occurs, so wasn’t sure if it’s a Symfony routing thing? Maybe in UriUpdater.php? Thanks I’m advance for any help

[EDIT]
Still no luck, but I've been trying to isolate where this happens and it seems to be in a couple of places, but main one is CollectionManager.php with the function 

```    /**
     * @return array<string, mixed>
     */
    public function getMetadata(int $tokenId, string $assetUri = null): array
    {
        $metadata = $this->collectionFilesystemDriver->getMetadata($this->getMappedTokenId($tokenId));

        foreach ($this->metadataUpdaters as $metadataUpdater) {
            $metadataUpdater->updateMetadata(
                $metadata,
                $tokenId,
                $assetUri ?? $this->urlGenerator->generate(
                    RouteName::GET_ASSET,
                    [
                        'tokenId' => $tokenId,
                        '_format' => $this->collectionFilesystemDriver->getAssetsExtension(),
                    ],
                    UrlGeneratorInterface::ABSOLUTE_URL,
                ),
            );
        }

        return $metadata;
    }
```

urlGenerator and generate() from from Symfony and I have no idea why RouteName::GET_ASSET would add those additional slashes - but perhaps something weird going on with GET_ASSET?

Any help appreciated.

**Comment by liarco** [comment]
Hi, that format is actually correct, the PHP serializer is strictly following the JSON specifications and escapes the `/` found in string values. Any good parsing library should support it with no problem.

For instance, you can open an [online JSON parser](https://jsonformatter.org/json-parser) and paste the following value:
```json
["http:\/\/mydigital-app.ondigitalocean.app\/asset\/1.png"]
```

You will see that the parsed value will be fine:
<img width="2046" alt="Screen Shot 2022-07-11 at 15 49 05" src="https://user-images.githubusercontent.com/1532277/178279261-6bc20d2a-fa6c-4804-87bf-3028df61bddb.png">

May I ask you which library/language is giving you `//` as result?

**Comment by kokako-loon** [comment]
Hi! Thanks for the response and although I didn't realize it, you are correct, the PHP serializer is strictly following the JSON specification. 

I see the `//` when I copy  `["http:\/\/mydigital-app.ondigitalocean.app\/asset\/1.png"]` and paste it directly in Chrome's address bar
