### ISSUE TITLE
DigitalOcean deployment fails in v2

### ISSUE THREAD

**Issue by MrMannoe** [hashlips-lab/safe-nft-metadata-provider#57]
Hi!

I've been using your app for a project and it's been brilliant :D. However, when I come to deploy onto DigitalOcean I receive the following error message:

`Error while creating app from Git template`
`Could not create app from Git template.`

`Getting owner: getting team data: rpc error: code = NotFound desc = team not found.`

This only occurs on the main / v2 branches. I briefly tried to look into what might be causing the issue but I haven't been able to figure it out.

**Comment by liarco** [comment]
Hi @MrMannoe, sorry for the late reply and thanks for reporting this. Seems like there is be something wrong on DigitalOcean's end (maybe they made some changes and we have to update accordingly).

I'm gonna reach out to them and provide some feedback on #58 which is about the same topic.

Thank you!

**Comment by liarco** [comment]
Update: https://github.com/hashlips-lab/safe-nft-metadata-provider/issues/58#issuecomment-1396193453
