### ISSUE TITLE
Adding 3D Models To Provider

### ISSUE THREAD

**Issue by nickyoung92** [hashlips-lab/safe-nft-metadata-provider#60]
Hello, first of all, thank you for this resource. It is invaluable.

Second, im trying to customize the code to protect glb files alongside pngs for the tokens. Do I need to make any changes in hashlips-lab/collection-data-updater? I added the following code to index.ts

`new S3BasicFileDataUpdater(
      "Model",
      s3Config,
      config.PRIVATE_MODELS_PATH,
      config.PUBLIC_MODELS_PATH,
      config.MODELS_EXTENSION,
    ),`

I also added these to config.ts

` PRIVATE_MODELS_PATH: getEnvironmentVariable("PRIVATE_MODELS_PATH"),
  PUBLIC_MODELS_PATH: getEnvironmentVariable("PUBLIC_MODELS_PATH"),
  MODELS_EXTENSION: getEnvironmentVariable("MODELS_EXTENSION"),`

and likewise, updated .do/deploy.template.yaml and .env with

`        - key: PRIVATE_MODELS_PATH
          scope: RUN_TIME
          value: /private/models
        - key: PUBLIC_MODELS_PATH
          scope: RUN_TIME
          value: /public/models
        - key: MODELS_EXTENSION
          scope: RUN_TIME
          value: .glb`

and 

`PRIVATE_MODELS_PATH=/private/models
PUBLIC_MODELS_PATH=/public/models
MODELS_EXTENSION=.glb`

respectively.

Everything deploys fine, and the png's and metadata get moved from private to public, but it seems to be ignoring the models, even within the runtime logs. Am I missing something? Perhaps you could make a short tutorial on how to customize the code to add an additional asset class?

Thank you for taking the time <3

**Comment by nickyoung92** [comment]
I figured it out. I had to update the deploy.template.yaml with my own git of the modified code.

```
git:
        branch: main
        repo_clone_url: https://github.com/nickyoung92/modelmetadataprovider.git
```

**Comment by liarco** [comment]
Hi @nickyoung92, I appreciate your feedback and I'm happy you have found this tool useful. :)

You are right! Any update to the code requires you to update the deployment configuration as well (I made a video tutorial long time ago about how to customize the tool using version `1.x`, the steps to deploy a customized version should be pretty much the same: https://www.youtube.com/watch?v=P1CsGuBO_Gs).

Just for your information: we are now focused on providing support and connecting directly with members of the Open Devs Crew (https://opendevs.io) so if you make use of our tools and maybe want to discuss some features and/or get some support you might be interested in joining at some point. It would also help us carrying on with development. ;)

Of course general maintenance and bug reports will be addressed publicly on GitHub whenever possible.

Thank you for reaching out and have a wonderful day! 😃
