### ISSUE TITLE
'Transaction reverted' error upon deployment 

### ISSUE THREAD

**Issue by HeresMyGit** [hashlips-lab/safe-nft-metadata-provider#61]
Hello,

I'm very excited to use this for my upcoming project!  I am trying to do a test run with a previously launched collection but running into an issue when I deploy on Digital Ocean.  It fails and gives me the error:

Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0xB941cB348C51f369326905E98371680Cf98b5Bb4","data":"0xd5abeb01","accessList":null}, error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":45,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0xb941cb348c51f369326905e98371680cf98b5bb4\",\"data\":\"0xd5abeb01\"},\"latest\"],\"id\":45,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://mainnet.infura.io/v3/my-api-key"}, code=CALL_EXCEPTION, version=providers/5.6.8)

If I take the transaction and try to run it in cURL I get the error:

{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"execution reverted"}}%      

I'm not sure what I'm doing wrong, I tried this with two of my ERC-721 contracts as well as the mfers NFT contract and I get the same error with all three of them.  I haven't made any changes to the project code either, although I do plan to in the near future.

Any suggestions?

**Comment by liarco** [comment]
Hi @HeresMyGit!
This project is compatible with our [own contract version](https://github.com/hashlips-lab/nft-erc721-collection), other contracts may require a custom [ERC721CollectionStatusProvider](https://github.com/hashlips-lab/collection-data-updater/blob/main/src/lib/CollectionStatusProviders/ERC721CollectionStatusProvider.ts) (my guess is your contract lacks the `maxSupply` value but I might be wrong).

Our support is currently limited to bug reports and security issues, but we provide priority support to all members of the [Open Devs Crew](https://opendevs.io/) so feel free to join if wish to ask questions to the team, get custom code examples, or influence the projects' roadmap. 💪 🚀

**Comment by HeresMyGit** [comment]
That did it, thank you so much for the reply!
